package com.mygdx.enumeration;

public enum CharacterSpriteEnum {
	ON_LOUIS_LEFT,
	ON_LOUIS_UP,
	ON_LOUIS_RIGHT,
	ON_LOUIS_DOWN,
	WALK_LEFT,
	WALK_UP,
	WALK_RIGHT,
	WALK_DOWN,
	CARRY_WALK_LEFT,
	CARRY_WALK_UP,
	CARRY_WALK_RIGHT,
	CARRY_WALK_DOWN,
	THROW_BOMBE_LEFT,
	THROW_BOMBE_UP,
	THROW_BOMBE_RIGHT,
	THROW_BOMBE_DOWN,
	VICTORY,
	ON_LOUIS_VICTORY,
	ANGRY,
	BURN,
	INSIDE_TROLLEY,
	SCORE_HAPPY,
	SCORE_CRY;
}
