language: java
sudo: false

addons:
  sonarcloud:
    organization: alexis-puska-github
    token:
      secure: 89b5352a550961e43b7633c060178ddbed5af637

script: 
    - ./gradlew assemble
    - sonar-scanner
